### ISSUE TITLE
Selective use of SIAM_OrgRefs.adl

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand-models#7]
#### Situation
I used SIAM selectively and I wanted to omit "SIAM_OrgRefs.adl", so I commented out the `INCLUDE "SIAM_OrgRefs.adl"`. However, this caused several compile errors, because other code in SIAMv4 uses relations declared in "SIAM_OrgRefs.adl". I expected that I can switch "SIAM_OrgRefs.adl" on and off as I please, but that didn't work.

#### Question
Is this a feature or a bug?

#### Versions
I used SIAMv4 from commit 25d632d70ed88aea97a4ea09a69df1fba122cdb7.

**Comment by RieksJ** [comment]
Yes, that doesn't work simply, for the rather obvious reason that `INCLUDE` works on files and there is no (standard) means to include/exclude features (that usually require code to be included/excluded in multiple files). 

Specifically, problems such as yours tend to occur if you also use one or more Interface-files (`.ifc` files) that are included in the module. One cannot predict what users want, so in the example loader file they are commented out to suggest they are there, but more to use as your own template than anything else.

As a rule of thumb, the minimum amount of stuff you need from SIAMv4 would be
- SIAM_AccountSessionRoels.adl
- SIAM_PersonRefs.adl
- SIAM_OrgRefs.adl
(perhaps one or two other files) and any interfaces you need.

If you do NOT want to use SIAMv4, but are forced to because the frontend has some relatively recent stuff dealing with menu-items and so, you may include the recently added file `SIAMv4_Stubs.adl`

Does that help? If so, please close the issue.

**Comment by RieksJ** [comment]
If we think that the ability to include/exclude features is called for, that should be made an issue which would then trigger me to add change requests to the conditional compiler constructs that are currently present (but apparently scarecely used)
